[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Bloqade = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe1"
BloqadeExpr = "bd27d05e-4ce1-5e79-84dd-c5d7d508abe2"
BloqadeKrylov = "bd27d05e-4cd1-5e79-84dd-c5d7d508ade2"
BloqadeLattices = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe4"
BloqadeMIS = "bd27d05e-4ce1-5e74-84dd-c5d7d508bbe2"
BloqadeODE = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe5"
BloqadeWaveforms = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe7"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoArrayRegister = "e600142f-9330-5003-8abb-0ebd767abc51"
YaoSubspaceArrayReg = "bd27d05e-4ce1-5e79-84dd-c5d7d508ade2"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
