[deps]
Bloqade = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe1"
BloqadeExpr = "bd27d05e-4ce1-5e79-84dd-c5d7d508abe2"
BloqadeKrylov = "bd27d05e-4cd1-5e79-84dd-c5d7d508ade2"
BloqadeLattices = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe4"
BloqadeMIS = "bd27d05e-4ce1-5e74-84dd-c5d7d508bbe2"
BloqadeODE = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe5"
BloqadeWaveforms = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe7"
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"
GenericTensorNetworks = "3521c873-ad32-4bb4-b63d-f4f178f42b49"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
YaoSubspaceArrayReg = "bd27d05e-4ce1-5e79-84dd-c5d7d508ade2"
