[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
Bloqade = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe1"
BloqadeExpr = "bd27d05e-4ce1-5e79-84dd-c5d7d508abe2"
BloqadeKrylov = "bd27d05e-4cd1-5e79-84dd-c5d7d508ade2"
BloqadeLattices = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe4"
BloqadeMIS = "bd27d05e-4ce1-5e74-84dd-c5d7d508bbe2"
BloqadeODE = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe5"
BloqadeWaveforms = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe7"
GenericTensorNetworks = "3521c873-ad32-4bb4-b63d-f4f178f42b49"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
YaoSubspaceArrayReg = "bd27d05e-4ce1-5e79-84dd-c5d7d508ade2"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
