name = "EaRyd"
uuid = "919886a7-1033-42c4-9b63-e090dad94c32"
authors = ["Roger-Luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ContinuousEmulator = "10fc086f-8aaa-4f44-9b62-28c43ef0af29"
CuRydbergEmulator = "6b142359-0b0c-4dfb-9c9b-84981bce612e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RydbergEmulator = "12dc9fdf-52a0-4520-b7fc-d1c1ff3ad2fe"

[compat]
CUDA = "3"
ContinuousEmulator = "0.4"
CuRydbergEmulator = "0.2"
Makie = "0.15"
Reexport = "1"
RydbergEmulator = "0.14"
julia = "1.6.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
