name = "Bloqade"
uuid = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe1"
version = "0.1.17"

[deps]
BloqadeExpr = "bd27d05e-4ce1-5e79-84dd-c5d7d508abe2"
BloqadeKrylov = "bd27d05e-4cd1-5e79-84dd-c5d7d508ade2"
BloqadeLattices = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe4"
BloqadeMIS = "bd27d05e-4ce1-5e74-84dd-c5d7d508bbe2"
BloqadeODE = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe5"
BloqadeWaveforms = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe7"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoSubspaceArrayReg = "bd27d05e-4ce1-5e79-84dd-c5d7d508ade2"

[compat]
BloqadeExpr = "0.1"
BloqadeKrylov = "0.1"
BloqadeLattices = "0.1"
BloqadeMIS = "0.1"
BloqadeODE = "0.1"
BloqadeWaveforms = "0.1"
ForwardDiff = "0.10"
Measurements = "2"
PythonCall = "0.8,0.9"
Reexport = "1"
Yao = "0.8"
YaoSubspaceArrayReg = "0.1"
julia = "1.6.3"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "Random"]
