[deps]
EaRyd = "919886a7-1033-42c4-9b63-e090dad94c32"
EaRydCUDA = "6b142359-0b0c-4dfb-9c9b-84981bce612e"
EaRydCore = "12dc9fdf-52a0-4520-b7fc-d1c1ff3ad2fe"
EaRydLattices = "0b2dfc99-25e4-4105-a7e4-4454e50c76c3"
EaRydODE = "10fc086f-8aaa-4f44-9b62-28c43ef0af29"
EaRydPlots = "12dc9fdf-52a0-4520-b7fc-d1c1ff3ad2f8"
EaRydWaveforms = "0b2dfc99-25e4-4105-a7e4-4454e50c76c1"
