[deps]
DocThemeIndigo = "8bac0ac5-51bf-41f9-885e-2bf1ac2bec5f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
EaRyd = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe1"
EaRydCUDA = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe3"
EaRydCore = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe2"
EaRydLattices = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe4"
EaRydODE = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe5"
EaRydPlots = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe6"
EaRydWaveforms = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe7"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
