[deps]
Bloqade = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe1"
BloqadeExpr = "bd27d05e-4ce1-5e79-84dd-c5d7d508abe2"
BloqadeGates = "9b473568-af80-491c-8f51-e251334462c1"
BloqadeKrylov = "bd27d05e-4cd1-5e79-84dd-c5d7d508ade2"
BloqadeLattices = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe4"
BloqadeMIS = "bd27d05e-4ce1-5e74-84dd-c5d7d508bbe2"
BloqadeODE = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe5"
BloqadeQMC = "2c0eea08-e05e-11ec-33df-b7e33af02477"
BloqadeSchema = "a64e8dd8-bb5a-11ec-104d-290571fc3a8d"
BloqadeWaveforms = "bd27d05e-4ce1-5e79-84dd-c5d7d508bbe7"
DocThemeIndigo = "8bac0ac5-51bf-41f9-885e-2bf1ac2bec5f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoAPI = "0843a435-28de-4971-9e8b-a9641b2983a8"
YaoArrayRegister = "e600142f-9330-5003-8abb-0ebd767abc51"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"
YaoSubspaceArrayReg = "bd27d05e-4ce1-5e79-84dd-c5d7d508ade2"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
